version: '3.3'
services:
  postgres:
    container_name: 'postgres-snobbin'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snobbin
    ports:
      - '5433:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
#  elasticsearch:
#    container_name: 'elasticsearch-snobbin'
#    image: elasticsearch:7.6.2
#    environment:
#      discovery.type: single-node
#    ports:
#      - '9200:9200'
  
volumes:
  postgresdata:
